### ISSUE TITLE
Check that patches are well documented

### ISSUE THREAD

**Issue by befeleme** [fedora-python/pull-request-review-guide#1]
Proposal by @hroncok:

```
- [ ] (when adding patches) Patch purpose is documented in the specfile
- [ ] (when backporting patches) Patch origin and/or authorship is traceable
```
 
I think it's a good idea which needs an explanation so it's clear what's the expectation of "passing" the check.

**Comment by hroncok** [comment]
Let's wait a couple of days for some thumbs up/down. I'll hopefully send a PR next week if there is consensus.

**Comment by hroncok** [comment]
OK. I see 2 :+1: and no :-1: and I will interpret it as "this is a good idea" because I'd hate to interpret it as "nobody really cares"
